name: '.NET code metrics'

on:
  push:
    branches: [ master ]
    paths-ignore:
    # Ignore CODE_METRICS.md and README.md files
    - '**.md'

# Create an environment variable named DOTNET_VERSION
# and set it as "6.0.x"
env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write

    steps:
    - uses: actions/checkout@v2
      
    # 2) Set up the .NET CLI environment for the workflow to use.
    #    The .NET version is specified by the environment variable.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # 3) Restore the dependencies and tools of a project or solution.
    - name: Install dependencies
      run: dotnet restore

    # 4) Build a project or solution and all of its dependencies.
    - name: Build
      run: dotnet build --configuration Release --no-restore -o Release

    # 5) Test a project or solution.
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    # Analyze repositories source metrics:
    # Create (or update) CODE_METRICS.md file.
    - name: .NET code metrics
      id: dotnet-code-metrics
      uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
      with:
        owner: ${{ github.repository_owner }}
        name: ${{ github.repository }}
        branch: ${{ github.ref }}
        dir: ${{ './Release' }}
        workspace: ${{ github.workspace }}

    - name: metrics summary
      id: dotnet-code-metrics-summary
      run: |
        echo "${{ steps.dotnet-code-metrics.outputs.summary-title }}"
        echo "${{ steps.dotnet-code-metrics.outputs.summary-details }}"

    # # Create a pull request if there are changes.
    # - name: Create pull request
    #   uses: peter-evans/create-pull-request@v3.4.1
    #   with:
    #     title: '${{ steps.dotnet-code-metrics.outputs.summary-title }}'
    #     body: '${{ steps.dotnet-code-metrics.outputs.summary-details }}'
    #     commit-message: '.NET code metrics, automated pull request.'